#pragma once

#include <string>
#include <vector>
#include <optional>
#include <cstdint>

#include "absl/status/status.h"

namespace ujfunc {

enum class ReturnCode : uint8_t {
  DONE = 0,
  NO_DATA,
  AWAIT,
  ERROR
};

// Await metadata
struct AwaitInfo {
  // The channel specifies which external subsystem should handle the pending computation to
  // resolve the awaited result.
  // E.g. "wgpu" for GPU operations, "timer" for time-based waits, etc.
  // In future this could also be used for subsystems fetching external data (as in web API
  // fetch) and use the result in computation.
  std::string channel;

  // This identifies the pending work within the specified channel.
  // The format of the workId is opaque to the core and is generated by the subsystem.
  // E.g. for "wgpu" channel, the function could prepare a description of the GPU pipeline
  // queue it for execution and use the returned workId to identify the pending GPU result.
  std::string workId;
};

// Missing input metadata
struct NoDataInfo {
  // Names of the function parameters (slots in the function node) which failed to execute because the
  // upstream data was missing.
  std::vector<std::string> missingSlots;
};

// Final return struct
struct FunctionReturn {
  ReturnCode code {ReturnCode::DONE};

  // Optional payloads (only one is active depending on code)
  std::optional<AwaitInfo> await;
  std::optional<NoDataInfo> noData;
  // ABSL status is used for error (code == ERROR) to leverage its rich ecosystem,
  // Must not use absl::okStatus(). For the special scenarios like NO_DATA and AWAIT,
  // do not use ERROR code, instead use the dedicated codes, otherwise the JS side
  // will not be able to distinguish them from regular errors.
  std::optional<absl::Status> error;  // only for ERROR

  // Lookup functions.
  bool IsDone()   const { return code == ReturnCode::DONE; }
  bool IsAwait()  const { return code == ReturnCode::AWAIT; }
  bool IsError()  const { return code == ReturnCode::ERROR; }
  bool IsNoData() const { return code == ReturnCode::NO_DATA; }
};

} // namespace ujfunc
